---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config
data:
  Corefile: |
    .:53 {
        file /etc/coredns/db.local local
        log
        errors
    }
  db.local: |
    $ORIGIN local.
    @    3600 IN SOA sns.dns.icann.org. noc.dns.icann.org. (
                                    2017042745 ; serial
                                    7200       ; refresh (2 hours)
                                    3600       ; retry (1 hour)
                                    1209600    ; expire (2 weeks)
                                    3600       ; minimum (1 hour)
                                    )

    test    IN A     172.16.3.200
    server  IN A     172.16.3.100
